name: app

type: php:7.3

runtime:
  extensions:
    - pdo_pgsql
    - apcu
    - mbstring
    - sodium


build:
  flavor: none

relationships:
  database: "db:postgresql"

web:
  locations:
    "/":
