version: '3'


services:
    database:
      image: postgres:11-alpine
      environment:
        POSTGRES_USER: main
        POSTGRES_PASSWORD: main
        POSTGRES_DB: main
        POSTGRES_HOST_AUTH_METHOD: 'trust'
        POSTGRES_HOST: db
      ports:
        - 5432/tcp






